# Generated by Django 5.2.4 on 2025-07-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('matematicas', 'Matemáticas'), ('tecnologia', 'Tecnología'), ('programacion', 'Programación'), ('ciencias', 'Ciencias'), ('letras', 'Letras'), ('relacionesHumanas', 'RelacionesHumanas'), ('empresas', 'Empresas'), ('humanidades', 'Humanidades')], max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
