# Generated by Django 5.2.4 on 2025-07-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_tiempo_limite_alter_curso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='frecuencia_personalizada',
            field=models.PositiveIntegerField(blank=True, help_text='Frecuencia personalizada en minutos', null=True),
        ),
    ]
