# Generated by Django 5.2.4 on 2025-07-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_frecuencia_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='frecuencia_personalizada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
