# Generated by Django 5.2.4 on 2025-07-23 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_frecuencia_personalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('completado', models.BooleanField(default=False)),
                ('avance', models.CharField(choices=[('bajo', 'Bajo (30%)'), ('medio', 'Medio (60%)'), ('alto', 'Alto (90%)')], default='bajo', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='cursos.curso')),
            ],
        ),
    ]
